# Generated by Django 4.2.1 on 2023-05-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=255)),
                ('closest_points', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'grid',
            },
        ),
    ]
